# Action for checking code with ESLint on pull requests
name: ESLint

# Triggers
on:
  pull_request:
    branches: [ main ]

# Workflow
jobs:
  # Lint job
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
